app/accounts/urls.py
from accounts.views import (
    AccountTemplateView,
    ChangePasswordView,
    LoginPageTemplateView,
    LoginView,
    LogoutView,
    ProtectedView,
)
from django.urls import path

app_name = "accounts"
urlpatterns = [
    path("login-api/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # path(
    #     "logout/",
    #     LogoutView.as_view(next_page="accounts:login_template"),
    #     name="logout",
    # ),
    path("login/", LoginPageTemplateView.as_view(), name="login_template"),
    path("protected/", ProtectedView.as_view(), name="protected"),
    path("account/", AccountTemplateView.as_view(), name="account_template"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
]

app/app/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from app.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", IndexView.as_view(), name="index_page"),
    # ToDo: Move password-related endpoints to accounts app.
    #  The problem with them is related to default Django HTML templates.
    #  We need to adjust URLs in them to include "account:" prefix.
    path(
        "password-reset/",
        PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset-done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

app/accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """Customized user model.

    Is needed in order to make it easier to customize User object later.
    """
    pass

app/vps_providers/models.py
from django.db import models

class VPSProvider(models.Model):
    name = models.CharField(max_length=100)
    website = models.URLField()
    # is_visible means if the provider is visible for our end customers on main page.
    is_visible = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "VPS Provider"
        verbose_name_plural = "VPS Providers"
        ordering = ['name']

app/accounts/views.py
import hashlib

from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
    update_session_auth_hash,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

User = get_user_model()


class LoginView(View):
    def post(self, request, *args, **kwargs):
        # Extract username and password from the request data
        username = request.POST.get("username")
        password = request.POST.get("password")

        # Authenticate the user
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return JsonResponse({"message": "Login successful"})
        else:
            return JsonResponse({"message": "Invalid credentials"}, status=400)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse("accounts:login_template"))


class ChangePasswordView(LoginRequiredMixin, View):
    """Change user password while user is logged in.

    This view should be triggered from account page while user is logged in.
    There will be another flow for users that forgot their passwords and want to
    change it.
    """

    def post(self, request, *args, **kwargs):
        # Extract current password and new password from the request data
        new_password1 = request.POST.get("new_password1")
        new_password2 = request.POST.get("new_password2")

        if new_password1 != new_password2:
            return JsonResponse({"message": "Passwords do not match"}, status=400)

        validate_password(new_password1, user=request.user)

        request.user.set_password(new_password1)
        request.user.save()

        # Update the session to prevent the user from being logged out
        update_session_auth_hash(request, request.user)

        return JsonResponse({"message": "Password changed successfully"})


# class ResetPasswordView(LoginRequiredMixin, View):
#     def post(self, request, *args, **kwargs):
#         # Extract email from the request data
#         email = request.POST.get("email")
#
#         try:
#             user = User.objects.get(email=email, is_active=True)
#         except User.DoesNotExist:
#             return JsonResponse(
#                 {
#                     "message": (
#                         "If the user with this email exists, "
#                         "a password reset email will be sent."
#                     )
#                 }
#             )
#
#         # Generate a password reset token
#         token = default_token_generator.make_token(user)
#
#         # Create a password reset URL
#         reset_url = request.build_absolute_uri(
#             reverse(
#                 "accounts:password_reset_confirm",
#                 kwargs={
#                     "uid": "sha3_256:" + hashlib.sha3_256(user.pk).hexdigest(),
#                     "token": token,
#                 },
#             )
#         )
#
#         # Send password reset email
#         subject = "DeFi Swimmer - Password Reset Request"
#         message = f"Please click the following link to reset your password: {reset_url}"
#         send_mail(subject, message, "noreply@defi-swimmer.com", [email])
#
#         return JsonResponse(
#             {
#                 "message": (
#                     "If the user with this email exists, "
#                     "a password reset email will be sent."
#                 )
#             }
#         )


# class PasswordResetConfirmationView(View):
#     def get(self, request, *args, **kwargs):
#         # Extract uidb64 and token from the URL
#         uid = kwargs.get("uid")
#         token = kwargs.get("token")
#
#         try:
#             # Decode the user id
#             uid = urlsafe_base64_decode(uid).decode()
#             user = User.objects.get(pk=uid)
#         except (TypeError, ValueError, OverflowError, User.DoesNotExist):
#             user = None
#
#         # Check if the user exists and the token is valid
#         if user is not None and default_token_generator.check_token(user, token):
#             # Token is valid, render password reset form
#             return JsonResponse(
#                 {
#                     "message": "Password reset link is valid",
#                     "uid": uid,
#                     "token": token,
#                 }
#             )
#         else:
#             # Invalid link
#             return JsonResponse(
#                 {"message": "Password reset link is invalid or has expired"}, status=400
#             )


class ProtectedView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return JsonResponse(
            {"message": f"This is a protected view for {request.user.username}"}
        )


class LoginPageTemplateView(TemplateView):
    template_name = "login_page.html"


class AccountTemplateView(TemplateView):
    template_name = "account_page.html"

app/app/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "app_index.html"

app/home_page/views.py
from django.shortcuts import render

# Create your views here.

app/accounts/templates/account_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account page</title>
    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
</head>
<body>
<header>
    <nav>
        <a href="/">Home page</a>
        <ul>
            <li><a href="{% url 'accounts:account_template' %}">Account</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        </ul>
    </nav>
</header>
<main>
    <section>
        <form action="{% url 'accounts:change_password' %}" method="POST">
            {% csrf_token %}
            <p><b>Change password</b></p>
            <label><b>New password</b></label>
            <input type="password" placeholder="**************" name="new_password1"
                   id="new-password1-input" required>

            <label><b>Repeat new password</b></label>
            <input type="password" placeholder="**************" name="new_password2"
                   id="new-password2-input" required>

            <button type="submit">Change</button>
        </form>
    </section>
</main>
</body>
</html>

app/accounts/templates/app_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DeFi Swimmer | Main page</title>
    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
</head>
<body>
<header>
    <nav>
        <a href="/">Home page</a>
        <ul>
            <li><a href="{% url 'accounts:account_template' %}">Account</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        </ul>
    </nav>
</header>
<main>
</main>
</body>
</html>

app/accounts/templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
</head>
<body>
<header>
    <nav>
        <a href="/">Home page</a>
        <ul>
            <li><a href="{% url 'accounts:account_template' %}">Account</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        </ul>
    </nav>
</header>
<main>
    <section>
        <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            <label for="username-input"><b>Username</b></label>
            <input type="text" placeholder="email@example.com" name="username"
                   id="username-input" required>

            <label for="password-input"><b>Password</b></label>
            <input type="password" placeholder="**************" name="password"
                   id="password-input" required>

            <button type="submit">Login</button>
            <p>
                <small>Forgot your password?</small>
            </p>
        </form>
    </section>
</main>
</body>
</html>

app/home_page/templates/home_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>VPS Compare</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css" />
    <script src="https://unpkg.com/hyperscript.org@0.9.12" defer></script>
  </head>
  <body>
    <nav class="navbar" role="navigation">
      <div class="navbar-menu">
        <div class="navbar-start">
          <a id="navbar-home-button" class="navbar-item" href="#">
            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 2L16.5 8.5L12 15L7.5 8.5L12 2Z" fill="#00d1b2" />
              <path d="M12 9L19.5 10.5L17 18L12 14L7 18L4.5 10.5L12 9Z" fill="#00bfa5" />
            </svg>
            VPS Compare
          </a>
          <a class="navbar-item" href="#">Other button</a>
        </div>
        <div class="navbar-end">
          <div id="navbar-account-dropdown" class="navbar-item dropdown">
            <div class="dropdown-trigger">
              <button
                class="button"
                _="on click toggle .is-active on #navbar-account-dropdown"
                aria-haspopup="true"
                aria-controls="dropdown-menu"
              >
                <span class="icon is-small">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <circle cx="12" cy="8" r="4" stroke="currentColor" stroke-width="2" />
                    <path
                      d="M6 18c0-3 3-5 6-5s6 2 6 5"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </span>
                <span>Your Username</span>
                <span class="icon is-small">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                      d="M7 10l5 5 5-5"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </span>
              </button>
            </div>
            <div class="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <a hfer="#" class="dropdown-item">Settings</a>
                <a hfer="#" class="dropdown-item">Change password</a>
                <hr class="dropdown-divider" />
                <a hfer="#" class="dropdown-item">Logout</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="is-flex is-justify-content-center mt-6">
      <table class="table is-hoverable is-size-6">
        <thead>
          <tr>
            <th>Rank</th>
            <th>Company</th>
            <th>Name</th>
            <th>vCPU</th>
            <th>RAM, GB</th>
            <th>Disk, GB</th>
            <th>OS available</th>
            <th>Location</th>
            <th>Price, $/mo</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>1</th>
            <td>Hostinger</td>
            <td>VPS-XS</td>
            <td>2</td>
            <td>4</td>
            <td>20</td>
            <td>Linux</td>
            <td>🇩🇪</td>
            <td>15.78</td>
          </tr>
          <tr>
            <th>2</th>
            <td>OVH Cloud</td>
            <td>VPS 16GB</td>
            <td>4</td>
            <td>16</td>
            <td>100</td>
            <td>Linux, Windows</td>
            <td>🇨🇿</td>
            <td>31.84</td>
          </tr>
          <tr>
            <th>3</th>
            <td>DigitalOcean</td>
            <td>Basic Droplet</td>
            <td>2</td>
            <td>8</td>
            <td>50</td>
            <td>Linux</td>
            <td>🇺🇸</td>
            <td>25.00</td>
          </tr>
          <tr>
            <th>4</th>
            <td>Linode</td>
            <td>Standard</td>
            <td>4</td>
            <td>16</td>
            <td>80</td>
            <td>Linux</td>
            <td>🇬🇧</td>
            <td>40.00</td>
          </tr>
          <tr>
            <th>5</th>
            <td>AWS</td>
            <td>t3.medium</td>
            <td>2</td>
            <td>8</td>
            <td>30</td>
            <td>Linux, Windows</td>
            <td>🇮🇪</td>
            <td>27.50</td>
          </tr>
          <tr>
            <th>6</th>
            <td>Vultr</td>
            <td>High Frequency</td>
            <td>3</td>
            <td>12</td>
            <td>60</td>
            <td>Linux</td>
            <td>🇳🇱</td>
            <td>35.00</td>
          </tr>
          <tr>
            <th>7</th>
            <td>Google Cloud</td>
            <td>n2-standard-4</td>
            <td>4</td>
            <td>16</td>
            <td>100</td>
            <td>Linux, Windows</td>
            <td>🇸🇬</td>
            <td>45.20</td>
          </tr>
          <tr>
            <th>8</th>
            <td>Azure</td>
            <td>B2s</td>
            <td>2</td>
            <td>4</td>
            <td>32</td>
            <td>Linux, Windows</td>
            <td>🇯🇵</td>
            <td>24.75</td>
          </tr>
          <tr>
            <th>9</th>
            <td>Hetzner</td>
            <td>CX21</td>
            <td>3</td>
            <td>8</td>
            <td>40</td>
            <td>Linux</td>
            <td>🇫🇮</td>
            <td>20.50</td>
          </tr>
          <tr>
            <th>10</th>
            <td>Scaleway</td>
            <td>Dev1-M</td>
            <td>4</td>
            <td>16</td>
            <td>100</td>
            <td>Linux, Windows</td>
            <td>🇫🇷</td>
            <td>37.60</td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
</html>